export const DONATE_REQUEST = 'DONATE_REQUEST';
export const DONATE_SUCCESS = 'DONATE_SUCCESS';
export const DONATE_FAILURE = 'DONATE_FAILURE';

export const SETPUBLISHABLEKEY_REQUEST = 'SETPUBLISHABLEKEY_REQUEST';
export const SETPUBLISHABLEKEY_SUCCESS = 'SETPUBLISHABLEKEY_SUCCESS';
export const SETPUBLISHABLEKEY_FAILURE = 'SETPUBLISHABLEKEY_FAILURE';

export const CREATETOKEN_REQUEST = 'CREATETOKEN_REQUEST';
export const CREATETOKEN_SUCCESS = 'CREATETOKEN_SUCCESS';
export const CREATETOKEN_FAILURE = 'CREATETOKEN_FAILURE';

export const RESET_SUCCESS = 'RESET_SUCCESS';

export const DONATE_COMPLETED = 'DONATE_COMPLETED';
export const DONATE_CANCELED = 'DONATE_CANCELED';
export const DONATE_NEW = 'DONATE_NEW';

